# Generated by Django 5.0.6 on 2024-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.EmailField(default='201212076@nileuniversity.edu.ng', max_length=254),
        ),
        migrations.AddField(
            model_name='advisor',
            name='phone_number',
            field=models.CharField(default='08182006962', max_length=15),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='areas_of_expertise',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Cybersecurity', 'Cybersecurity'), ('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology')], max_length=50),
        ),
    ]
