# Generated by Django 5.0.6 on 2024-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0003_alter_advisor_office_hours_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved_by_advisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='approved_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
