# Generated by Django 5.0.6 on 2024-05-26 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0004_appointment_approved_by_advisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Advisor.advisor'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Cybersecurity', 'Cybersecurity'), ('Software Engineering', 'Software Engineering'), ('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='201212076@nileuniversity.edu.ng', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='08182006962', max_length=15),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='areas_of_expertise',
            field=models.CharField(choices=[('Cybersecurity', 'Cybersecurity'), ('Software Engineering', 'Software Engineering'), ('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science')], max_length=50),
        ),
    ]
