# Generated by Django 5.0.6 on 2024-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0006_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
